CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY,
    uuid TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tags_uuid ON tags(uuid);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(name);