// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ttt_service.proto

package ttt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	context "todo-time-tracker/proto/context"
	tag "todo-time-tracker/proto/tag"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagReq) Reset() {
	*x = GetTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReq) ProtoMessage() {}

func (x *GetTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReq.ProtoReflect.Descriptor instead.
func (*GetTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *tag.Tag               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagResp) Reset() {
	*x = GetTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResp) ProtoMessage() {}

func (x *GetTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResp.ProtoReflect.Descriptor instead.
func (*GetTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagResp) GetTag() *tag.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ListTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // Could add pagination later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReq) Reset() {
	*x = ListTagsReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReq) ProtoMessage() {}

func (x *ListTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReq.ProtoReflect.Descriptor instead.
func (*ListTagsReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTagsReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type ListTagsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*tag.Tag             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResp) Reset() {
	*x = ListTagsResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResp) ProtoMessage() {}

func (x *ListTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResp.ProtoReflect.Descriptor instead.
func (*ListTagsResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTagsResp) GetTags() []*tag.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReq) Reset() {
	*x = CreateTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReq) ProtoMessage() {}

func (x *CreateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReq.ProtoReflect.Descriptor instead.
func (*CreateTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *tag.Tag               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResp) Reset() {
	*x = CreateTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResp) ProtoMessage() {}

func (x *CreateTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResp.ProtoReflect.Descriptor instead.
func (*CreateTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTagResp) GetTag() *tag.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type UpdateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagReq) Reset() {
	*x = UpdateTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagReq) ProtoMessage() {}

func (x *UpdateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagReq.ProtoReflect.Descriptor instead.
func (*UpdateTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *tag.Tag               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResp) Reset() {
	*x = UpdateTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResp) ProtoMessage() {}

func (x *UpdateTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResp.ProtoReflect.Descriptor instead.
func (*UpdateTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTagResp) GetTag() *tag.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type DeleteTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagReq) Reset() {
	*x = DeleteTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagReq) ProtoMessage() {}

func (x *DeleteTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagReq.ProtoReflect.Descriptor instead.
func (*DeleteTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResp) Reset() {
	*x = DeleteTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResp) ProtoMessage() {}

func (x *DeleteTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResp.ProtoReflect.Descriptor instead.
func (*DeleteTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{9}
}

var File_proto_ttt_service_proto protoreflect.FileDescriptor

const file_proto_ttt_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ttt_service.proto\x12\x03ttt\x1a\x0fproto/tag.proto\x1a\x13proto/context.proto\"K\n" +
	"\tGetTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"(\n" +
	"\n" +
	"GetTagResp\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"9\n" +
	"\vListTagsReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\",\n" +
	"\fListTagsResp\x12\x1c\n" +
	"\x04tags\x18\x01 \x03(\v2\b.tag.TagR\x04tags\"N\n" +
	"\fCreateTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\rCreateTagResp\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"b\n" +
	"\fUpdateTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"+\n" +
	"\rUpdateTagResp\x12\x1a\n" +
	"\x03tag\x18\x01 \x01(\v2\b.tag.TagR\x03tag\"N\n" +
	"\fDeleteTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"\x0f\n" +
	"\rDeleteTagResp2\x84\x02\n" +
	"\n" +
	"TTTService\x12)\n" +
	"\x06GetTag\x12\x0e.ttt.GetTagReq\x1a\x0f.ttt.GetTagResp\x12/\n" +
	"\bListTags\x12\x10.ttt.ListTagsReq\x1a\x11.ttt.ListTagsResp\x122\n" +
	"\tCreateTag\x12\x11.ttt.CreateTagReq\x1a\x12.ttt.CreateTagResp\x122\n" +
	"\tUpdateTag\x12\x11.ttt.UpdateTagReq\x1a\x12.ttt.UpdateTagResp\x122\n" +
	"\tDeleteTag\x12\x11.ttt.DeleteTagReq\x1a\x12.ttt.DeleteTagRespB\x1dZ\x1btodo-time-tracker/proto/tttb\x06proto3"

var (
	file_proto_ttt_service_proto_rawDescOnce sync.Once
	file_proto_ttt_service_proto_rawDescData []byte
)

func file_proto_ttt_service_proto_rawDescGZIP() []byte {
	file_proto_ttt_service_proto_rawDescOnce.Do(func() {
		file_proto_ttt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ttt_service_proto_rawDesc), len(file_proto_ttt_service_proto_rawDesc)))
	})
	return file_proto_ttt_service_proto_rawDescData
}

var file_proto_ttt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ttt_service_proto_goTypes = []any{
	(*GetTagReq)(nil),       // 0: ttt.GetTagReq
	(*GetTagResp)(nil),      // 1: ttt.GetTagResp
	(*ListTagsReq)(nil),     // 2: ttt.ListTagsReq
	(*ListTagsResp)(nil),    // 3: ttt.ListTagsResp
	(*CreateTagReq)(nil),    // 4: ttt.CreateTagReq
	(*CreateTagResp)(nil),   // 5: ttt.CreateTagResp
	(*UpdateTagReq)(nil),    // 6: ttt.UpdateTagReq
	(*UpdateTagResp)(nil),   // 7: ttt.UpdateTagResp
	(*DeleteTagReq)(nil),    // 8: ttt.DeleteTagReq
	(*DeleteTagResp)(nil),   // 9: ttt.DeleteTagResp
	(*context.Context)(nil), // 10: context.Context
	(*tag.Tag)(nil),         // 11: tag.Tag
}
var file_proto_ttt_service_proto_depIdxs = []int32{
	10, // 0: ttt.GetTagReq.context:type_name -> context.Context
	11, // 1: ttt.GetTagResp.tag:type_name -> tag.Tag
	10, // 2: ttt.ListTagsReq.context:type_name -> context.Context
	11, // 3: ttt.ListTagsResp.tags:type_name -> tag.Tag
	10, // 4: ttt.CreateTagReq.context:type_name -> context.Context
	11, // 5: ttt.CreateTagResp.tag:type_name -> tag.Tag
	10, // 6: ttt.UpdateTagReq.context:type_name -> context.Context
	11, // 7: ttt.UpdateTagResp.tag:type_name -> tag.Tag
	10, // 8: ttt.DeleteTagReq.context:type_name -> context.Context
	0,  // 9: ttt.TTTService.GetTag:input_type -> ttt.GetTagReq
	2,  // 10: ttt.TTTService.ListTags:input_type -> ttt.ListTagsReq
	4,  // 11: ttt.TTTService.CreateTag:input_type -> ttt.CreateTagReq
	6,  // 12: ttt.TTTService.UpdateTag:input_type -> ttt.UpdateTagReq
	8,  // 13: ttt.TTTService.DeleteTag:input_type -> ttt.DeleteTagReq
	1,  // 14: ttt.TTTService.GetTag:output_type -> ttt.GetTagResp
	3,  // 15: ttt.TTTService.ListTags:output_type -> ttt.ListTagsResp
	5,  // 16: ttt.TTTService.CreateTag:output_type -> ttt.CreateTagResp
	7,  // 17: ttt.TTTService.UpdateTag:output_type -> ttt.UpdateTagResp
	9,  // 18: ttt.TTTService.DeleteTag:output_type -> ttt.DeleteTagResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_ttt_service_proto_init() }
func file_proto_ttt_service_proto_init() {
	if File_proto_ttt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ttt_service_proto_rawDesc), len(file_proto_ttt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ttt_service_proto_goTypes,
		DependencyIndexes: file_proto_ttt_service_proto_depIdxs,
		MessageInfos:      file_proto_ttt_service_proto_msgTypes,
	}.Build()
	File_proto_ttt_service_proto = out.File
	file_proto_ttt_service_proto_goTypes = nil
	file_proto_ttt_service_proto_depIdxs = nil
}
