// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ttt_service.proto

package ttt

import (
	reflect "reflect"
	sync "sync"
	context "todo-time-tracker/proto/go/context"
	model "todo-time-tracker/proto/go/model"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -- User operations --
type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *model.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResp) GetUser() *model.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagReq) Reset() {
	*x = GetTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReq) ProtoMessage() {}

func (x *GetTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReq.ProtoReflect.Descriptor instead.
func (*GetTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *model.Tag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagResp) Reset() {
	*x = GetTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResp) ProtoMessage() {}

func (x *GetTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResp.ProtoReflect.Descriptor instead.
func (*GetTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTagResp) GetTag() *model.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ListTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // Could add pagination later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsReq) Reset() {
	*x = ListTagsReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsReq) ProtoMessage() {}

func (x *ListTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsReq.ProtoReflect.Descriptor instead.
func (*ListTagsReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListTagsReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type ListTagsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*model.Tag           `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResp) Reset() {
	*x = ListTagsResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResp) ProtoMessage() {}

func (x *ListTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResp.ProtoReflect.Descriptor instead.
func (*ListTagsResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListTagsResp) GetTags() []*model.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReq) Reset() {
	*x = CreateTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReq) ProtoMessage() {}

func (x *CreateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReq.ProtoReflect.Descriptor instead.
func (*CreateTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *model.Tag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResp) Reset() {
	*x = CreateTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResp) ProtoMessage() {}

func (x *CreateTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResp.ProtoReflect.Descriptor instead.
func (*CreateTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTagResp) GetTag() *model.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type UpdateTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagReq) Reset() {
	*x = UpdateTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagReq) ProtoMessage() {}

func (x *UpdateTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagReq.ProtoReflect.Descriptor instead.
func (*UpdateTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *model.Tag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResp) Reset() {
	*x = UpdateTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResp) ProtoMessage() {}

func (x *UpdateTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResp.ProtoReflect.Descriptor instead.
func (*UpdateTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTagResp) GetTag() *model.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type DeleteTagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagReq) Reset() {
	*x = DeleteTagReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagReq) ProtoMessage() {}

func (x *DeleteTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagReq.ProtoReflect.Descriptor instead.
func (*DeleteTagReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTagReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteTagReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteTagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResp) Reset() {
	*x = DeleteTagResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResp) ProtoMessage() {}

func (x *DeleteTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResp.ProtoReflect.Descriptor instead.
func (*DeleteTagResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{11}
}

type CreateTaskReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Context           *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status            model.Task_Status      `protobuf:"varint,4,opt,name=status,proto3,enum=model.Task_Status" json:"status,omitempty"`
	EstimatedDuration *durationpb.Duration   `protobuf:"bytes,5,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTaskReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskReq) GetStatus() model.Task_Status {
	if x != nil {
		return x.Status
	}
	return model.Task_Status(0)
}

func (x *CreateTaskReq) GetEstimatedDuration() *durationpb.Duration {
	if x != nil {
		return x.EstimatedDuration
	}
	return nil
}

type CreateTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *model.Task            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResp) Reset() {
	*x = CreateTaskResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResp) ProtoMessage() {}

func (x *CreateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResp.ProtoReflect.Descriptor instead.
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTaskResp) GetTask() *model.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTaskReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *model.Task            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResp) Reset() {
	*x = GetTaskResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResp) ProtoMessage() {}

func (x *GetTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResp.ProtoReflect.Descriptor instead.
func (*GetTaskResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskResp) GetTask() *model.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type LinkTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *context.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	FromTaskUuid  string                 `protobuf:"bytes,2,opt,name=from_task_uuid,json=fromTaskUuid,proto3" json:"from_task_uuid,omitempty"`
	ToTaskUuid    string                 `protobuf:"bytes,3,opt,name=to_task_uuid,json=toTaskUuid,proto3" json:"to_task_uuid,omitempty"`
	Link          model.Task_Link        `protobuf:"varint,4,opt,name=link,proto3,enum=model.Task_Link" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkTasksReq) Reset() {
	*x = LinkTasksReq{}
	mi := &file_proto_ttt_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTasksReq) ProtoMessage() {}

func (x *LinkTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTasksReq.ProtoReflect.Descriptor instead.
func (*LinkTasksReq) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{16}
}

func (x *LinkTasksReq) GetContext() *context.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *LinkTasksReq) GetFromTaskUuid() string {
	if x != nil {
		return x.FromTaskUuid
	}
	return ""
}

func (x *LinkTasksReq) GetToTaskUuid() string {
	if x != nil {
		return x.ToTaskUuid
	}
	return ""
}

func (x *LinkTasksReq) GetLink() model.Task_Link {
	if x != nil {
		return x.Link
	}
	return model.Task_Link(0)
}

type LinkTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkTasksResp) Reset() {
	*x = LinkTasksResp{}
	mi := &file_proto_ttt_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTasksResp) ProtoMessage() {}

func (x *LinkTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ttt_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTasksResp.ProtoReflect.Descriptor instead.
func (*LinkTasksResp) Descriptor() ([]byte, []int) {
	return file_proto_ttt_service_proto_rawDescGZIP(), []int{17}
}

var File_proto_ttt_service_proto protoreflect.FileDescriptor

const file_proto_ttt_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ttt_service.proto\x12\x03ttt\x1a\x11proto/model.proto\x1a\x13proto/context.proto\x1a\x1egoogle/protobuf/duration.proto\"\x81\x01\n" +
	"\rCreateUserReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"1\n" +
	"\x0eCreateUserResp\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.model.UserR\x04user\"K\n" +
	"\tGetTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"*\n" +
	"\n" +
	"GetTagResp\x12\x1c\n" +
	"\x03tag\x18\x01 \x01(\v2\n" +
	".model.TagR\x03tag\"9\n" +
	"\vListTagsReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\".\n" +
	"\fListTagsResp\x12\x1e\n" +
	"\x04tags\x18\x01 \x03(\v2\n" +
	".model.TagR\x04tags\"N\n" +
	"\fCreateTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"-\n" +
	"\rCreateTagResp\x12\x1c\n" +
	"\x03tag\x18\x01 \x01(\v2\n" +
	".model.TagR\x03tag\"b\n" +
	"\fUpdateTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"-\n" +
	"\rUpdateTagResp\x12\x1c\n" +
	"\x03tag\x18\x01 \x01(\v2\n" +
	".model.TagR\x03tag\"N\n" +
	"\fDeleteTagReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"\x0f\n" +
	"\rDeleteTagResp\"\xe7\x01\n" +
	"\rCreateTaskReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.model.Task.StatusR\x06status\x12H\n" +
	"\x12estimated_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11estimatedDuration\"1\n" +
	"\x0eCreateTaskResp\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.model.TaskR\x04task\"L\n" +
	"\n" +
	"GetTaskReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\".\n" +
	"\vGetTaskResp\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.model.TaskR\x04task\"\xa8\x01\n" +
	"\fLinkTasksReq\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.context.ContextR\acontext\x12$\n" +
	"\x0efrom_task_uuid\x18\x02 \x01(\tR\ffromTaskUuid\x12 \n" +
	"\fto_task_uuid\x18\x03 \x01(\tR\n" +
	"toTaskUuid\x12$\n" +
	"\x04link\x18\x04 \x01(\x0e2\x10.model.Task.LinkR\x04link\"\x0f\n" +
	"\rLinkTasksResp2\xd4\x03\n" +
	"\n" +
	"TTTService\x125\n" +
	"\n" +
	"CreateUser\x12\x12.ttt.CreateUserReq\x1a\x13.ttt.CreateUserResp\x12)\n" +
	"\x06GetTag\x12\x0e.ttt.GetTagReq\x1a\x0f.ttt.GetTagResp\x12/\n" +
	"\bListTags\x12\x10.ttt.ListTagsReq\x1a\x11.ttt.ListTagsResp\x122\n" +
	"\tCreateTag\x12\x11.ttt.CreateTagReq\x1a\x12.ttt.CreateTagResp\x122\n" +
	"\tUpdateTag\x12\x11.ttt.UpdateTagReq\x1a\x12.ttt.UpdateTagResp\x122\n" +
	"\tDeleteTag\x12\x11.ttt.DeleteTagReq\x1a\x12.ttt.DeleteTagResp\x125\n" +
	"\n" +
	"CreateTask\x12\x12.ttt.CreateTaskReq\x1a\x13.ttt.CreateTaskResp\x12,\n" +
	"\aGetTask\x12\x0f.ttt.GetTaskReq\x1a\x10.ttt.GetTaskResp\x122\n" +
	"\tLinkTasks\x12\x11.ttt.LinkTasksReq\x1a\x12.ttt.LinkTasksRespB\x0eZ\fproto/go/tttb\x06proto3"

var (
	file_proto_ttt_service_proto_rawDescOnce sync.Once
	file_proto_ttt_service_proto_rawDescData []byte
)

func file_proto_ttt_service_proto_rawDescGZIP() []byte {
	file_proto_ttt_service_proto_rawDescOnce.Do(func() {
		file_proto_ttt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ttt_service_proto_rawDesc), len(file_proto_ttt_service_proto_rawDesc)))
	})
	return file_proto_ttt_service_proto_rawDescData
}

var file_proto_ttt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_ttt_service_proto_goTypes = []any{
	(*CreateUserReq)(nil),       // 0: ttt.CreateUserReq
	(*CreateUserResp)(nil),      // 1: ttt.CreateUserResp
	(*GetTagReq)(nil),           // 2: ttt.GetTagReq
	(*GetTagResp)(nil),          // 3: ttt.GetTagResp
	(*ListTagsReq)(nil),         // 4: ttt.ListTagsReq
	(*ListTagsResp)(nil),        // 5: ttt.ListTagsResp
	(*CreateTagReq)(nil),        // 6: ttt.CreateTagReq
	(*CreateTagResp)(nil),       // 7: ttt.CreateTagResp
	(*UpdateTagReq)(nil),        // 8: ttt.UpdateTagReq
	(*UpdateTagResp)(nil),       // 9: ttt.UpdateTagResp
	(*DeleteTagReq)(nil),        // 10: ttt.DeleteTagReq
	(*DeleteTagResp)(nil),       // 11: ttt.DeleteTagResp
	(*CreateTaskReq)(nil),       // 12: ttt.CreateTaskReq
	(*CreateTaskResp)(nil),      // 13: ttt.CreateTaskResp
	(*GetTaskReq)(nil),          // 14: ttt.GetTaskReq
	(*GetTaskResp)(nil),         // 15: ttt.GetTaskResp
	(*LinkTasksReq)(nil),        // 16: ttt.LinkTasksReq
	(*LinkTasksResp)(nil),       // 17: ttt.LinkTasksResp
	(*context.Context)(nil),     // 18: context.Context
	(*model.User)(nil),          // 19: model.User
	(*model.Tag)(nil),           // 20: model.Tag
	(model.Task_Status)(0),      // 21: model.Task.Status
	(*durationpb.Duration)(nil), // 22: google.protobuf.Duration
	(*model.Task)(nil),          // 23: model.Task
	(model.Task_Link)(0),        // 24: model.Task.Link
}
var file_proto_ttt_service_proto_depIdxs = []int32{
	18, // 0: ttt.CreateUserReq.context:type_name -> context.Context
	19, // 1: ttt.CreateUserResp.user:type_name -> model.User
	18, // 2: ttt.GetTagReq.context:type_name -> context.Context
	20, // 3: ttt.GetTagResp.tag:type_name -> model.Tag
	18, // 4: ttt.ListTagsReq.context:type_name -> context.Context
	20, // 5: ttt.ListTagsResp.tags:type_name -> model.Tag
	18, // 6: ttt.CreateTagReq.context:type_name -> context.Context
	20, // 7: ttt.CreateTagResp.tag:type_name -> model.Tag
	18, // 8: ttt.UpdateTagReq.context:type_name -> context.Context
	20, // 9: ttt.UpdateTagResp.tag:type_name -> model.Tag
	18, // 10: ttt.DeleteTagReq.context:type_name -> context.Context
	18, // 11: ttt.CreateTaskReq.context:type_name -> context.Context
	21, // 12: ttt.CreateTaskReq.status:type_name -> model.Task.Status
	22, // 13: ttt.CreateTaskReq.estimated_duration:type_name -> google.protobuf.Duration
	23, // 14: ttt.CreateTaskResp.task:type_name -> model.Task
	18, // 15: ttt.GetTaskReq.context:type_name -> context.Context
	23, // 16: ttt.GetTaskResp.task:type_name -> model.Task
	18, // 17: ttt.LinkTasksReq.context:type_name -> context.Context
	24, // 18: ttt.LinkTasksReq.link:type_name -> model.Task.Link
	0,  // 19: ttt.TTTService.CreateUser:input_type -> ttt.CreateUserReq
	2,  // 20: ttt.TTTService.GetTag:input_type -> ttt.GetTagReq
	4,  // 21: ttt.TTTService.ListTags:input_type -> ttt.ListTagsReq
	6,  // 22: ttt.TTTService.CreateTag:input_type -> ttt.CreateTagReq
	8,  // 23: ttt.TTTService.UpdateTag:input_type -> ttt.UpdateTagReq
	10, // 24: ttt.TTTService.DeleteTag:input_type -> ttt.DeleteTagReq
	12, // 25: ttt.TTTService.CreateTask:input_type -> ttt.CreateTaskReq
	14, // 26: ttt.TTTService.GetTask:input_type -> ttt.GetTaskReq
	16, // 27: ttt.TTTService.LinkTasks:input_type -> ttt.LinkTasksReq
	1,  // 28: ttt.TTTService.CreateUser:output_type -> ttt.CreateUserResp
	3,  // 29: ttt.TTTService.GetTag:output_type -> ttt.GetTagResp
	5,  // 30: ttt.TTTService.ListTags:output_type -> ttt.ListTagsResp
	7,  // 31: ttt.TTTService.CreateTag:output_type -> ttt.CreateTagResp
	9,  // 32: ttt.TTTService.UpdateTag:output_type -> ttt.UpdateTagResp
	11, // 33: ttt.TTTService.DeleteTag:output_type -> ttt.DeleteTagResp
	13, // 34: ttt.TTTService.CreateTask:output_type -> ttt.CreateTaskResp
	15, // 35: ttt.TTTService.GetTask:output_type -> ttt.GetTaskResp
	17, // 36: ttt.TTTService.LinkTasks:output_type -> ttt.LinkTasksResp
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_ttt_service_proto_init() }
func file_proto_ttt_service_proto_init() {
	if File_proto_ttt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ttt_service_proto_rawDesc), len(file_proto_ttt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ttt_service_proto_goTypes,
		DependencyIndexes: file_proto_ttt_service_proto_depIdxs,
		MessageInfos:      file_proto_ttt_service_proto_msgTypes,
	}.Build()
	File_proto_ttt_service_proto = out.File
	file_proto_ttt_service_proto_goTypes = nil
	file_proto_ttt_service_proto_depIdxs = nil
}
