version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tttdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tttdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grpc-server:
    build:
      context: ../../
      dockerfile: cmd/server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/tttdb?sslmode=disable
    ports:
      - "50051:50051"
    restart: unless-stopped

volumes:
  postgres_data: