// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/context.proto

package context

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Context message
type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_proto_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_proto_context_proto protoreflect.FileDescriptor

const file_proto_context_proto_rawDesc = "" +
	"\n" +
	"\x13proto/context.proto\x12\acontext\"%\n" +
	"\aContext\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busernameB!Z\x1ftodo-time-tracker/proto/contextb\x06proto3"

var (
	file_proto_context_proto_rawDescOnce sync.Once
	file_proto_context_proto_rawDescData []byte
)

func file_proto_context_proto_rawDescGZIP() []byte {
	file_proto_context_proto_rawDescOnce.Do(func() {
		file_proto_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_context_proto_rawDesc), len(file_proto_context_proto_rawDesc)))
	})
	return file_proto_context_proto_rawDescData
}

var file_proto_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_context_proto_goTypes = []any{
	(*Context)(nil), // 0: context.Context
}
var file_proto_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_context_proto_init() }
func file_proto_context_proto_init() {
	if File_proto_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_context_proto_rawDesc), len(file_proto_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_context_proto_goTypes,
		DependencyIndexes: file_proto_context_proto_depIdxs,
		MessageInfos:      file_proto_context_proto_msgTypes,
	}.Build()
	File_proto_context_proto = out.File
	file_proto_context_proto_goTypes = nil
	file_proto_context_proto_depIdxs = nil
}
